save:
  folder_name: merged30_test
  
train:
  folder_name: merged30
  
data_dir:
  data_list_dir: ./data/merged30/TEST/labels/test_list.pkl
  labels_path: False

infer:
  th: 0.75 #0.75
  top_k : 10
  batch_size: 48
  workers: 8
  model_path: ./result/train/merged30/models/model-highest.ckpt    #model-highest.ckpt