results_dir: "./exp1/"
wandb_opt: False

data_dir:
  block_train: "./data/train.csv"

data:
  val_ratio: 0.2

train:
  seed: 41
  epoch: 100
  batch_size: 64
  lr: 0.0003
  num_workers: 4
  data:
    img_size: 224
  using_existed_merged_exp: train_merge8 # or False

generating:
  folder_name: merged9
  train_target_sample_num: 5000 #5000
  val_target_sample_num: 1250 #1250
  auto_block_size: False
  same_class_generate: 
    option: True
    ratio: 1
    over_num: 2
    generating: False
    

