results_dir: "./exp1/"
wandb_opt: False

data_dir:
  block_train: "../data/train.csv"


train:
  seed: 41
  epoch: 30
  batch_size: 64
  lr: 0.0003
  num_workers: 4
  data:
    img_size: 224


generating:
  delete_merge_folder: True
  train_generate_num: 9000
  val_generate_num: 3000
  folder_name: merged1
  train_one_sample_num: 20
  val_one_sample_num: 10
