results_dir: "./exp1/"
wandb_opt: False

data_dir:
  block_train: "../data/train.csv"


train:
  seed: 41
  epoch: 30
  batch_size: 64
  lr: 0.0003
  num_workers: 4
  data:
    img_size: 224


generating:
  delete_merge_folder: True
  train_generate_num_list: [0,0,0,0,3000,3000,3000,3000,3000,3000]
  val_generate_num_list: [0,0,0,0,2000,2000,2000,2000,2000,2000]
  folder_name: merged4
  
  generate_sampling_ratio: 0.5
  generate_sampling_limit_num: 10

  train_target_sample_num: 3000
  val_target_sample_num: 2000
  same_class_generate: 
    option: True
    ratio: 1
    over_num: 5
    

