results_dir: "./exp1/"
wandb_opt: False

data_dir:
  block_train: "../data/train.csv"


train:
  seed: 41
  epoch: 30
  batch_size: 64
  lr: 0.0003
  num_workers: 4
  data:
    img_size: 224


generating:
  delete_merge_folder: False
  train_generate_num_list: [0,0,0,0,5000,5000,5000,5000,5000,5000]
  val_generate_num_list: [0,0,0,0,3000,3000,3000,3000,3000,3000]
  folder_name: merged4
  
  generate_sampling_ratio: 0.5
  generate_sampling_limit_num: 10

  train_target_sample_num: 5000
  val_target_sample_num: 3000
  same_class_generate: 
    option: True
    ratio: 1
    over_num: 5
    

